### ISSUE TITLE
Debug Ember Times 87

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-times-tools#17]
Noting for later https://emberjs.com/blog/2019/03/01/the-ember-times-issue-87.html, I will help

```
Editing content (9/9)
Finished editing content (9/9)
Drag "Social Links" to the bottom (below "#embertimes", above "Footer")  🤖...
(node:6118) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'boundingBox' of null
    at createTemplate (/Users/amyrlam/src/ember/emberjs-times-tools/create-goodbits-template.js:192:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by amyrlam** [comment]
I think some stuff in the Goodbits UI has changed. 

Had trouble scrolling down the LHS where the content is, just had to `command -` instead to get drag and drop of the LHS to work

**Comment by amyrlam** [comment]
I'm going to close all the new issues and start again now that me and @tylerturdenpants have paired and debugged!
