### ISSUE TITLE
Puppeteer - Delete extra blank line at the end of each section

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-learn/ember-times-tools#3]

**Comment by tylerturdenpants** [comment]
from @amyrlam 
```
Visiting https://emberjs.com/blog/2018/12/21/the-ember-times-issue-78.html ...
Collected text content from 9 sections to copy.
Visiting https://goodbits.io/users/sign_in ...
Logged in successfully ✨
Adding intro....
Added intro. ✨
Editing content (1/8)
Finished editing content (1/8)
Editing content (2/8)
Finished editing content (2/8)
Editing content (3/8)
(node:6291) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __puppeteer_evaluation_script__:7:31
    at ExecutionContext.evaluateHandle (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:124:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:144:27)
    at ExecutionContext.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/FrameManager.js:447:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/Page.js:777:43)
    at Page.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:145:23)
    at addContentBlockRoutine (/Users/amyrlam/src/ember/emberjs-times-tools/create-goodbits-template.js:263:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

then it just hangs...

I rolled back to a prior commit to get to finish.

I will try to take a further look 🔜
```

**Comment by jayjayjpg** [comment]
I added a guard against the last div (which sometimes might be e.g. an `ul`) in this [PR](https://github.com/jessica-jordan/emberjs-times-tools/pull/9) and did a test run against the latest blog post: https://www.emberjs.com/blog/2018/12/21/the-ember-times-issue-78.html

**Comment by amyrlam** [comment]
Working great! 

Found a minor exception? If ends in a hyperlink, adds a blank line e.g. this paragraph https://emberjs.com/blog/2019/01/25/the-ember-times-issue-82.html#toc_a-href-http-ember-decorators-github-io-ember-decorators-decorate-today-the-ember-way-a

**Comment by amyrlam** [comment]
I think we can just close by noting hyperlink at end of section as a known issue in the README, what do you think

**Comment by amyrlam** [comment]
Closing all of the issues and starting fresh post-pair sesh with Ryan.
