### ISSUE TITLE
goodbits made changes?

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-times-tools#34]
don't have time to look into this rn...the homepage def looks different. but let's look into it next week @tylerturdenpants @jessica-jordan 

(same issue with #125 URL that worked last week)

```
amyrlam@amyrlamComputer ember-times-tools (master) 🌒 $ node create-goodbits-template.js --botemail="$GOODBITS_USER_EMAIL" --botpassword="$GOODBITS_USER_PASSWORD" --botblogurl="https://blog.emberjs.com/2019/11/29/the-ember-times-issue-126.html"
Visiting https://blog.emberjs.com/2019/11/29/the-ember-times-issue-126.html ...
Collected text content from 10 sections to copy.
Visiting https://goodbits.io/users/login ...
(node:25402) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'setAttribute' of null
    at __puppeteer_evaluation_script__:5:39
    at ExecutionContext.evaluateHandle (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/helper.js:110:27)
    at ExecutionContext.evaluate (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluate (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/Page.js:782:43)
    at Page.<anonymous> (/Users/amyrlam/src/ember/ember-times-tools/node_modules/puppeteer/lib/helper.js:111:23)
    at createTemplate (/Users/amyrlam/src/ember/ember-times-tools/lib/create-template.js:36:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jayjayjpg** [comment]
Nooo, this needed to happen at one point lol. I can check this week if this is straightforward to fix and send a PR if that's the case :+1:

**Comment by jayjayjpg** [comment]
I reproduced the issue using

```
node create-goodbits-template.js --botemail="$GOODBITS_USER_EMAIL" --botpassword="$GOODBITS_USER_PASSWORD" --botblogurl="https://blog.emberjs.com/2019/11/29/the-ember-times-issue-126.html"
```

and it seems that luckily only the domain of goodbits has changed for the homepage and the emails overview page. I can send a PR in a bit!

**Comment by jayjayjpg** [comment]
Addressed with https://github.com/ember-learn/ember-times-tools/pull/35 I think
